[GLOBAL]

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black"
]
pants_version = "2.18.2"

[python]
interpreter_constraints = ["==3.10.*"]
enable_resolves = true

[generate-lockfiles]
diff = true
