[GLOBAL]
pants_version = "2.14.2"
backend_packages = [
    "pants.backend.shell",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.docker"
]

[python]
enable_resolves = true
interpreter_constraints = [">=3.10"]

[python.resolves]
python-default="sample.lock"
