[GLOBAL]
pants_version = "2.15.1"
backend_packages = [
    "pants.backend.shell",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.docker"
]

[python]
enable_resolves = true

[python.resolves]
logic1 = "logic1.lock"
logic2 = "logic2.lock"
