[GLOBAL]

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.isort",
]
pants_version = "2.18.2"

[source]
root_patterns = [
  "/",
  "/app1/",
  "/app2/",
]

[python]
enable_resolves = true
interpreter_constraints = ["==3.10.*"]

[generate-lockfiles]
diff = true

[test]
use_coverage = true
