[GLOBAL]
pants_version = "2.17.0rc0"
backend_packages = [
    "pants.backend.shell",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.docker"
]

[python]
enable_resolves = true
interpreter_constraints = [">=3.10"]

[python.resolves]
python-default="sample.lock"

[source]
root_patterns = [
    'logic1/',
    'logic2/'
]
